### ISSUE TITLE
html 자동완성이 안되는데 도움이 필요합니다.

### ISSUE THREAD

**Issue by wideep3** [SeongJaeMoon/FastCampusWebPythonBasic#2]
제가 패스트 캠퍼스 python 강좌도 함께 듣는데, 파이썬 강좌 따라하고 나서 오늘 html강좌를 따라하다 보니

html 자동 완성이 안되는데 어떻게 설정값을 바꿔야 하는지 알려주시면 감사하겠습니다.

**Comment by ghost** [comment]
http://www.homejjang.com/05/autocomplete.php
자동완성 태그 온 하시면 될까요?
이것 물어보신게 맞으실지..

2019년 5월 1일 수요일, wideep3 <notifications@github.com>님이 작성:

**Comment by ajskd5** [comment]
-----Original Message-----

**Comment by kdjpassion2** [comment]
firebase-tools 설치와 로그인이 진행이 되지 않습니다. 도움 부탁드립니다.

PS C:\WINDOWS\system32> npm install -g firebase-tools
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated fsevents@2.1.3: Please update to v 2.2.x
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

changed 615 packages, and audited 616 packages in 21s

19 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\WINDOWS\system32> firebase login
firebase : 이 시스템에서 스크립트를 실행할 수 없으므로 C:\Users\USER\AppData\Roaming\npm\firebase.ps1 파일을 로드할 수
없습니다. 자세한 내용은 about_Execution_Policies(https://go.microsoft.com/fwlink/?LinkID=135170)를 참조하십시오.
위치 줄:1 문자:1
+ firebase login
+ ~~~~~~~~
    + CategoryInfo          : 보안 오류: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
